name: trackonnections
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  app_links: ^6.3.2
  auth_buttons: ^3.0.3
  flutter:
    sdk: flutter
  flutter_appauth: ^8.0.1
  flutter_local_notifications: ^18.0.1
  flutter_map: ^7.0.2
  flutter_sound: ^9.17.8
  flutter_web_auth: ^0.6.0
  flutter_webview_plugin: ^0.4.0
  geolocator: ^13.0.2
  google_maps: ^8.1.1
  google_maps_flutter: ^2.10.0
  google_maps_flutter_web: ^0.5.10
  google_sign_in: ^6.2.2
  latlong2: ^0.9.1
  maps_launcher: ^2.2.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  spotify: ^0.13.7
  spotify_sdk: ^3.0.2
  uni_links: ^0.5.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
